apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ng-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: ng-static-pv
  selector:
    matchLabels:
      type: ng-pods-label
