apiVersion: v1
kind: PersistentVolume
metadata:
  name: ng-static-pv
  labels:
    type: ng-pods-label
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/SharedDirectory"
    # path: "/mnt/data/Portfolio-Frontend/build"
  # claimRef:   it is very important because through labels connections pv is not connecting to pvc while through  claimRef: it is connecting correctly
  claimRef:
    namespace: django-react
    name: ng-static-pvc
