apiVersion: v1
kind: Service
metadata:
  name: ng-service
spec:
  # type: NodePort
  type: ClusterIP
  selector:
    app: ng-pods-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 31345
