apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-html-pv
  labels:
    type: nginx-html-label
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/Portfolio-Frontend/build"
  claimRef:
    namespace: default
    name: nginx-html-pvc
