apiVersion: v1
kind: PersistentVolume
metadata:
  name: bk-conf-pv
  labels:
    type: bk-conf-pv-label
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/django"
  claimRef:
    namespace: django-react
    name: bk-conf-pvc
