apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bk-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: bk-media-pv
  selector:
    matchLabels:
      type: bk-media-pv-label
