apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bk-static-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: bk-static-pv
  selector:
    matchLabels:
      type: bk-static-pv-label
