apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ng-pods-label
  template:
    metadata:
      labels:
        app: ng-pods-label
    spec:
      containers:
        - name: ng
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-django-secret
                  key: secret-key
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-django-secret
                  key: postgres-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-django-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-django-secret
                  key: postgres-password
          volumeMounts:
            - mountPath: "/PortfolioBackend/PortfolioBackend/settings.py"
              name: bk-pv-volume
              subPath: settings.py
            - mountPath: /PortfolioBackend/staticdirectory
              name: shared-storage
              subPath: staticdirectory
            - mountPath: /PortfolioBackend/Media
              name: shared-storage
              subPath: Media
      volumes:
        - name: bk-pv-volume
          configMap:
            name: bk-settings-cm
        - name: bk-pv-volume02
          configMap:
            name: bk-gunicorn-cm
        - name: shared-storage
          persistentVolumeClaim:
            claimName: bk-static-pvc
        # - name: existing-static
        #   emptyDir: {} # Use an empty directory for temporary storage during init
        # - name: existing-media
        #   emptyDir: {} # Use an empty directory for temporary storage during init
