apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgre-pv-d
  # labels:
  # type: postgre-type
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/postgresql02/data"
  # claimRef:   it is very important because through labels connections pv is not connecting to pvc while through  claimRef: it is connecting correctly
  claimRef:
    namespace: django-namespace
    name: postgre-pvc-d
