apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-pvc-d
  namespace: django-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # selector:
  # matchLabels:
  # type: postgres-type
