apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-con-label
  template:
    metadata:
      labels:
        app: node-con-label
    spec:
      containers:
        - name: node-con
          image: ajmalkhanbangash/afd-app:0.1
          ports:
            - containerPort: 80
