apiVersion: v1
kind: Service
metadata:
  name: bk-service
spec:
  type: NodePort
  selector:
    app: bk-pods-label
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32001
