apiVersion: v1
kind: PersistentVolume
metadata:
  name: bk-static-pv
  labels:
    type: bk-static-pv-label
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # path: "/mnt/data/Portfolio-Frontend/build"
  # claimRef:   it is very important because through labels connections pv is not connecting to pvc while through  claimRef: it is connecting correctly
  claimRef:
    namespace: django-react
    name: bk-static-pvc
