apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bk-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: bk-static-pv
  selector:
    matchLabels:
      type: bk-static-pv-label
