apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing
  # annotations:
  # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: nginx02.ajmal.com
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: nginx-service02
          #       port:
          #         number: 80
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-ing
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   rules:
#     - host: nginx02.ajmal.com
#       http:
#         paths:
#           - path: /app(/|$)(.*)
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: nginx-service
#                 port:
#                   number: 80
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: nginx-service02
#                 port:
#                   number: 80

