apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-psql-pvc-data-initdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: db-psql-pv-data-initdb
