apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
  labels:
    app: postgres
data:
  init.sql: |
    CREATE USER hamad WITH PASSWORD 'passwd-hamad-302';
    CREATE DATABASE hamad_db;
    GRANT ALL PRIVILEGES ON DATABASE hamad_db TO hamad;
