apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-psql-pv-data-initdb
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/init-db.sh
  claimRef:
    namespace: django-react
    name: db-psql-pvc-data-initdb
