# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: db-psql-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   volumeName: db-psql-pv
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: postgre-pv
