apiVersion: v1
kind: PersistentVolume
metadata:
  name: ngdp-pv
  labels:
    type: ngdp-pv-label
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/configuration02"
  claimRef:
    namespace: default
    name: ngdp-pvc
