# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: sf-pv
#   labels:
#     type: sf-label
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: "/mnt/data/Portfolio-Frontend/build"
#   claimRef:
#     namespace: default
#     name: sf-pvc
# /////////////////////////////////////////////////////////////////////////////////////////////////////
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sf-pv
  labels:
    type: sf-label
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/Portfolio-Frontend/build"
  claimRef:
    namespace: default
    name: sf-pvc
