apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fr-pods-label
  template:
    metadata:
      labels:
        app: fr-pods-label
    spec:
      containers:
        - name: fr-con
          # image: ajmalkhanbangash/port-frontend:0.0.6
          image: port-frontend:0.0.6
          # image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/etc/nginx/nginx.conf"
              name: fr-conf-pv-volume
              subPath: nginx.conf
      volumes:
        - name: fr-conf-pv-volume
          configMap:
            name: fr-conf-cm
          # persistentVolumeClaim:
          #   claimName: ng-conf-pvc
