apiVersion: v1
kind: PersistentVolume
metadata:
  name: sf-conf-pv
  labels:
    type: sf-conf-label
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/configuration"
  claimRef:
    namespace: default
    name: sf-conf-pvc
