apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginxx-pv
  labels:
    type: nginxx-pv-label
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/configuration"
    # path: "/mnt/data/Portfolio-Frontend/build"
  # claimRef:   it is very important because through labels connections pv is not connecting to pvc while through  claimRef: it is connecting correctly
  claimRef:
    namespace: default
    name: nginxx-pvc
