apiVersion: v1
kind: Service
metadata:
  name: nginxx-service
spec:
  # type: NodePort
  selector:
    app: nginxx-pods-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 32000
