apiVersion: v1
kind: Service
metadata:
  name: nginxx-service
spec:
  type: NodePort
  selector:
    app: nginxx-pods-label
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 31345
