apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxx-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxx-pods-label
  template:
    metadata:
      labels:
        app: nginxx-pods-label
    spec:
      containers:
        - name: nginxx-container
          # image: ajmalkhanbangash/afd-app:0.1
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            # - mountPath: "/usr/share/nginx/html"
            # name: ngdp-pv-volume
            - mountPath: "/etc/nginx/conf.d"
              name: nginxx-pv-volume
      volumes:
        # - name: ngdp-pv-volume
        #   persistentVolumeClaim:
        #     claimName: nginx-pvc
        - name: nginxx-pv-volume
          persistentVolumeClaim:
            claimName: nginxx-pvc
