apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-conf-pv
  labels:
    type: frontend-conf-pv-label
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/configuration02"
  claimRef:
    namespace: portfolio
    name: frontend-conf-pvc
