apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-static-pv
  labels:
    type: frontend-static-pv-label
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/Portfolio-Frontend/build"
  # claimRef:   it is very important because through labels connections pv is not connecting to pvc while through  claimRef: it is connecting correctly
  claimRef:
    namespace: portfolio
    name: frontend-static-pvc
